version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ../webservice_crm
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
     SPRING_APPLICATION_JSON: '{
        "server.port":8084,
        "crm.superAdmin":"admin",
        "server.error.include-message":"always",
        "project.version":"crmwebService.1.0",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql":true,
        "spring.jpa.properties.hibernate.format_sql":true,
        "security.basic.enable": false,
        "crm.app.jwtSecret":"cr.comSecretKey",
        "crm.app.jwtExpiration":86400,
        "logging.level.org.springframework.mail":"DEBUG",
        "spring.mail.host":"smtp.gmail.com",
        "spring.mail.port":587,
        "spring.mail.username":"graphalterebsg@gmail.com",
        "spring.mail.password":"G123456789@",
        "spring.mail.properties.mail.smtp.auth":true,
        "spring.mail.properties.mail.smtp.connectiontimeout":5000,
        "spring.mail.properties.mail.smtp.timeout":5000,
        "spring.mail.properties.mail.smtp.writetimeout":5000,
        "spring.mail.properties.mail.smtp.starttls.enable":true,
        "mail.subject.add.customer":"Ajout admin",
        "spring.servlet.multipart.enabled":true,
        "spring.servlet.multipart.max-file-size":"10MB",
        "spring.servlet.multipart.max-request-size":"15MB"

      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:

